### ISSUE TITLE
Can your library be used as an Express.js middleware?

### ISSUE THREAD

**Issue by paulocoghi** [delvedor/fast-json-body#1]
First of all, congratulations on your achievement!

I would like to know if you design your library to be used as an alternative to the Express middleware [body-parser](https://github.com/expressjs/body-parser).

Thanks!

**Comment by paulocoghi** [comment]
Sorry, now I understand your library better and I have used it properly inside a new middleware. Thanks!

**Comment by delvedor** [comment]
Yes you can use it, but this library needs some update, for example it's not checking for the body size, so you should use it only with trusted sources.
